apiVersion: v1
kind: Service
metadata:
  name: phpma-service
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpma
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - protocol: TCP
      name: phpma-port
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpma-deployment
  labels:
    app: phpma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpma
  template:
    metadata:
      labels:
        app: phpma
    spec:
      containers:
      - name: phpma
        image: phpma-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

